### ISSUE TITLE
Tool use guidelines

### ISSUE THREAD

**Issue by jeanpm** [microsoft/Trace#16]
Hi everyone,

Thanks for open-sourcing your code; this is an amazing framework. 

My question concerns tool use, i.e., providing predefined functions/methods so Trace can generate code _using_ them (calling instead of defining the functions). Are there any guidelines on how to do it? How did you envision this type of scenario? 

From my attempts, I understand it is possible to provide a list of tool descriptions as part of Feedback or even as part of the objective prompt to the optimizer. Still, is there a proper way more aligned with what you envisioned?

**Comment by allenanie** [comment]
Ching-An can chime in here, but you can write an orchestration function like this.

```python
@bundle()
def call_tool_1(param1, param2, ...):
  """
  Tool 1 is about .... (description of tool 1)
  input, output to Tool 1
  """
  return calling_external_api()

@bundle()
def call_tool_2(param1, param2, ...):
  """
  Description of tool 2
  """
  return calling_external_api()

@bundle(trainable=True)
def act(query):
   """
   Decide which tool to call, available tools: tool_1, tool_2
   """
   result = call_tool_1(param1, param2)
   return
```

Note that, both `call_tool_1` and `call_tool_2` are not changed / fixed by Trace, but `act` can change!
The docstrings you provide to all three functions are visible to the Trace optimizers. These became your "prompts". 

You don't have to provide a list of tool descriptions as feedback.

**Comment by allenanie** [comment]
Exactly -- the docstring is the prompt/explanation on what the tool is about and how it should be used. It can be long :)

**Comment by jeanpm** [comment]
Your approach worked great in my toy example :) Providing the list of tools as part of the docstring I get something like

```python
def act() -> bool:
    """Perform car maintenance for the cheapest price possible. Use the available tools below if necessary.
   ...
    - setup_vehicle(): Sets up the vehicle for deployment (incurr a cost)
    - calibrate_sensors(): Calibrates vehicle sensors (incurr a cost).
    - perform_safety_checks(): Performs safety checks on the vehicle (incurr a cost).
    - deploy_vehicle(): Deploys the vehicle if ready (incurr a cost).
    - perform_maintenance(): Performs maintenance on the vehicle if necessary (incurr a cost).
    - validate_vehicle(): Validates the vehicle before deployment (incurr a cost).
    - calibrate_and_check_sensors(): Calibrate sensors and perform safety checks in parallel (incurr a cost).
    """
    if not is_vehicle_ready():
        setup_vehicle()
        print('Vehicle was set up.')
        return False
    if not are_sensors_calibrated() or not are_safety_checks_passed():
        calibrate_and_check_sensors()
        print('Sensors calibrated and safety checks performed.')
    if is_maintenance_required():
        perform_maintenance()
        print('Maintenance performed.')
    if not is_vehicle_deployed():
        deploy_vehicle()
        print('Vehicle deployed.')
    return True)
``` 
where the tools/functions are being used correctly.

However, in my previous version (including the list in the feedback string), I could dynamically include the list of tools, while here, they are hardcoded in the docstring. Do you have any suggestions about that? (I tried to update the act.info[doc] to change the list of tools in the docstring dynamically but did not work )

**Comment by chinganc** [comment]
Hi @jeanpm , if you want to dynamically change the description of the bundled operator, you can change the `description` attribute, i.e., `act.description`. Note when overwriting it, you need to follow its syntax of '[$op_name]  $description' The attribute was constructed from docstring if it's not manually provided (see https://github.com/microsoft/Trace/blob/4e6fad28d3b4c044baae8ce1ab670b45204041e9/opto/trace/bundle.py#L124C9-L124C25). Let me know if it works.

**Comment by jeanpm** [comment]
Hi @chinganc , thanks for the suggestion but I couldnt make it work that way (seems like the optimizer is unaware of the tools if I include them as part of the description only). I'll dig deeper in the code later, but for now I'll move forward using the feedback (or objective) string.
